### ISSUE TITLE
Add and document jar argument

### ISSUE THREAD

**Issue by ryantheleach** [jpenilla/run-task#14]
When developing paper plugins, occasionally it is useful to know when it's being run inside a dev environment.

Adding a jar argument or environment variable to run-paper would allow plugins to enable extra debug behavior when running from a debugging environment.

**Comment by ryantheleach** [comment]
Note `doPause` inside `net.minecraft.Util#doPause` && `net.minecraft.SharedConstants#IS_RUNNING_IN_IDE`

**Comment by jpenilla** [comment]
I don't think it's appropriate to set Minecraft's IDE flag indiscriminately, when debugging plugins it's not particularly useful.

I'll set the `xyz.jpenilla.run-task` system property to to `true` though.
