### ISSUE TITLE
run velocity?

### ISSUE THREAD

**Issue by OskarZyg** [jpenilla/run-task#20]
Could this project be extended to run velocity? They use the same download API and all it would require is some arguments to be changed, but if that's out of the scope of this project that's understandable.

**Comment by 4drian3d** [comment]
It would be really quite useful a plugin like _run-velocity_ or diversify this project to support velocity or waterfall (although waterfall is almost deprecated so the best would be just Velocity)

**Comment by Peter-Crawley** [comment]
This would be nice

**Comment by jpenilla** [comment]
This is something I would like to implement, one thing to think about is what to rename the parent project/repo to once it has both run-paper and run-velocity.

**Comment by OskarZyg** [comment]
`run-server` seems fair

**Comment by Peter-Crawley** [comment]
did this idea just die out?

**Comment by OskarZyg** [comment]
never really started as anything other than an issue, someone will probably make one eventually

**Comment by KotlinFactory** [comment]
Would be amazing if it could do it.

**Comment by jpenilla** [comment]
Implemented in 2.0.0

https://plugins.gradle.org/plugin/xyz.jpenilla.run-paper
https://plugins.gradle.org/plugin/xyz.jpenilla.run-waterfall
https://plugins.gradle.org/plugin/xyz.jpenilla.run-velocity
