### ISSUE TITLE
Enable colours by default 

### ISSUE THREAD

**Issue by masmc05** [jpenilla/run-task#28]
I think most people that uses this could profit from adding by default
```kts
     runMojangMappedServer {
        systemProperty("terminal.jline", false)
        systemProperty("terminal.ansi", true)
    }
    runServer {
        systemProperty("terminal.jline", false)
        systemProperty("terminal.ansi", true)
    }
```

to enable colours like 
![image](https://github.com/jpenilla/run-task/assets/63639746/b1e73d1b-a752-4064-a896-85bf16f6c613)

Because most people using this will run from ide, and it will be useful for them (you can add a method that automatically remove this if you want)

Most people don't even know you can do that

**Comment by jpenilla** [comment]
There isn't any difference between having these properties set or not on the latest 1.20.1 Paper build. I'm guessing you tested with an older version?

Regardless, I don't think it's the place of run-task to try and patch incompatibilities (that exist regardless of the presence of run-task) between IntelliJ's terminal emulators and the software we are launching.

Any issues with IntelliJ's terminal emulators should be directed to JetBrains, and any issues about Paper's feature detection to Paper (they might redirect you to KyoriPowered/ansi).
