### ISSUE TITLE
Unable to accept EULA

### ISSUE THREAD

**Issue by AstralBaby** [jpenilla/run-task#29]
Hi, i'm using the latest release of paper and im unable to accept eula from JavaExec  args.
![image](https://github.com/jpenilla/run-task/assets/67666284/ad7b1911-95d0-4182-ab95-3a5f0ce3e38b)

works with previous versions of paper 😳👌

**Comment by jpenilla** [comment]
System properties are specified via JVM args (ie `jvmArgs("-Dcom.mojang.eula.agree=true")`), not program args. Alternatively, you could use the `systemProperty(name, value)` helper method.
