### ISSUE TITLE
Support dependecy jars.

### ISSUE THREAD

**Issue by thegatesdev** [jpenilla/run-task#34]
Hello! When working on a single minecraft plugin, this task works really well!
However, some of my work uses multiple projects, published to private repositories.
EDIT This means that I cannot use any of the 'downloadPlugins' options, they wouldn't account for authentication and such.
EDIT 2 Also this would remove duplication, chances are you already have a library plugin as a dependency, and now this is duplicated in the 'downloadPlugins' section.

Would it be possible to add a feature that adds jars from selected dependencies in the project to the server plugins?
It could look something like this:
```kt
runServer{
    minecraftVersion("1.20.1")
    localPlugins{ // Couldn't think of a better name
         fromDependency("io.github.thegatesdev:someplugin:1.0.0")
   }
}
```

Thanks!

**Comment by jpenilla** [comment]
If a plugin is on a maven repo you don't need to use downloadPlugins. Just create a configuration and add the dep, then use pluginJars.from(configuration).
