### ISSUE TITLE
run-paper in multi-module projects

### ISSUE THREAD

**Issue by thatbakamono** [jpenilla/run-task#37]
Is it possible to use `run-task` in projects with multiple modules? 

I have a configuration like:
```
XYZ:
- plugin1
- plugin2
- plugin3
```
and I'd like to be able to run it on `XYZ` and have all three plugins built and included.

I haven't seen any examples like that in the readme or on the wiki, it also didn't seem to work while I tried but there's a chance I did something wrong.

**Comment by jpenilla** [comment]
you probably want to apply the plugin to the root project, and in it's build script do something like
```kotlin
tasks.runServer {
  pluginJars.from(project(":path-to-project").tasks.[jar/shadowJar/reobfJar].flatMap { it.[archiveFile/outputJar] })
}
```
(in groovy can skip `a.flatMap { it.b }` and do `a.b`)
