### ISSUE TITLE
Ability to reference multi-project plugins

### ISSUE THREAD

**Issue by misterquestions** [jpenilla/run-task#46]
Hey there, first of all, this gradle plugin is just awesome.

I was wondering if it would be possible to allow the "download"/including plugins from referenced projects so in a gradle multi-project build being able to include/reference projects that are plugins would be really handy when it comes to dependencies.

Thanks in advance.

Edit: I've seen some people already requested this and seen some solution using `pluginJars` but imo feels a bit hacky and adds complexity as you'll need to ensure such jar exists by building the project, it might be easier for anyone to simply reference it with the project directive (just like when you do on dependencies block for example `implementation(project(":my-project"))`), meaning it will be built and the output jar will be used into the runServer task along with the current project jar.

**Comment by jpenilla** [comment]
pluginJars is a ConfigurableFileCollection, you are free to add files from a dependency Configuration
