### ISSUE TITLE
Is it possible to run from local copy of Folia?

### ISSUE THREAD

**Issue by tmvkrpxl0** [jpenilla/run-task#70]
Folia for 1.21.1 is not released as of now, and there is only the source code for it. Is it possible to use `run-task` with local clone of Paper/Folia? I have already built it from source.

**Comment by tmvkrpxl0** [comment]
Technically `serverJar` would work, but I'm curious to know if it can just run the project itself and not go through jar process

**Comment by jpenilla** [comment]
You can put anything Gradle supports onto the runClasspath ConfigurableFileCollection, and setting the main class works the same as a normal JavaExec.
