### ISSUE TITLE
Paper Mojang Mapped config option.

### ISSUE THREAD

**Issue by nicolube** [jpenilla/run-task#83]
Hello,

I'm trying to debug MC nms stuff and to make that easier I would to prefer to run the mojmapped jar avalible with paper 120.4 and smaller.

Is there already support for that or can support for that be added?

**Comment by jpenilla** [comment]
Apply the paperweight-userdev plugin and use the runDevBundleServer task. No plans to add a way to download Mojang mapped jars for these old versions, debugging the server without correct sources is not very useful due to line mapping issues.
