### ISSUE TITLE
Error loading java agent with jdk-16

### ISSUE THREAD

**Issue by Wyne10** [jpenilla/run-task#87]
Hello,

I'm trying to run minecraft 1.16.5, but i keep getting "error loading java agent" error.
I can run any minecraft version >1.16.5 using jdk 17+ just fine, but versions <1.17 with jdk <17 won't start.

I'm running gradle 8.10.2
[Build scan](https://scans.gradle.com/s/thk7kpvrqkbvs)

**Comment by jpenilla** [comment]
run task doesn't specify any java agent, if you have questions about running various Paper versions on various JDK versions you should ask in the Paper Discord.
